### ISSUE TITLE
cannot find resnet-12 results in the published paper

### ISSUE THREAD

**Issue by Tsingularity** [yaoyao-liu/E3BM#2]
Hi, thanks for the great work and releasing your code!

In the Readme, the results on resnet-12 under transductive setting are given for E3bm. However, I cannot find those numbers in the published paper. So I am just wondering is something wrong here?

Thanks!

**Comment by yaoyao-liu** [comment]
In the readme file, we include results using ResNet-12 in the inductive setting. These results are provided in Table S1 (supplementary, [link](http://www.ecva.net/papers/eccv_2020/papers_ECCV/papers/123610392-supp.pdf)).

If you have any further questions, feel free to leave comments here.

Best,
Yaoyao

**Comment by Tsingularity** [comment]
cool! thanks!
